import { AssigneeGenderEnum } from "../modules/assignees/models/Assignee";

export const assigneeFakeData = [
  {
    id: 1,
    name: "Étienne Henry",
    email: "Aleaume_Pierre@yahoo.fr",
    phone: "0436707047",
    gender: AssigneeGenderEnum.MAN,
  },
  {
    id: 2,
    name: "Daphné Clement",
    email: "Aliette.Morel@yahoo.fr",
    phone: "+33 610975921",
    gender: AssigneeGenderEnum.WOMEN,
  },
  {
    id: 3,
    name: "Daniel Olivier",
    email: "Alcibiade_Riviere75@hotmail.fr",
    phone: "0648575275",
    gender: AssigneeGenderEnum.MAN,
  },
  {
    id: 4,
    name: "Aloyse Poirier",
    email: "Jrme_Muller43@yahoo.fr",
    phone: "0588778834",
    gender: AssigneeGenderEnum.MAN,
  },
  {
    id: 5,
    name: "M Émilie Brunet",
    email: "Abeline.Clement@yahoo.fr",
    phone: "0505846763",
    gender: AssigneeGenderEnum.WOMEN,
  },
  {
    id: 6,
    name: "Clovis Roger",
    email: "Raphal_Fournier42@yahoo.fr",
    phone: "0275261249",
    gender: AssigneeGenderEnum.WOMEN,
  },
  {
    id: 7,
    name: "Dr Inès Jean",
    email: "Achaire25@yahoo.fr",
    phone: "0175049975",
    gender: AssigneeGenderEnum.WOMEN,
  },
  {
    id: 8,
    name: "Anselme Marty",
    email: "Jade_Morin@yahoo.fr",
    phone: "0573990480",
    gender: AssigneeGenderEnum.MAN,
  },
  {
    id: 9,
    name: "Samuel Brun",
    email: "Mlisande.Muller@gmail.com",
    phone: "0411642608",
    gender: AssigneeGenderEnum.MAN,
  },
  {
    id: 10,
    name: "Axel Menard",
    email: "Chlo.Dumas29@gmail.com",
    phone: "+33 345418159",
    gender: AssigneeGenderEnum.WOMEN,
  },
];

export const todoFakeData = [
  {
    id: 1,
    title: "aut omnis repudiandae",
    assigneeId: 5,
    startDate: "2024-04-30T13:02:19.552Z",
    endDate: "2024-11-22T03:50:47.379Z",
    prority: "2",
    labels: ["2", "3"],
    description:
      "Quia voluptatem fuga. Praesentium quae placeat aut sunt impedit non eos ipsa eaque. Aliquam rem quasi molestiae ipsa eaque similique.",
  },
  {
    id: 2,
    title: "magnam in exercitationem",
    assigneeId: 9,
    startDate: "2024-04-30T22:39:30.980Z",
    endDate: "2024-07-22T11:23:59.316Z",
    prority: "3",
    labels: ["3"],
    description:
      "Voluptatem laborum quis eveniet non id voluptatem numquam. Quas eos quasi ab molestias et dolor non sit. Sit exercitationem accusantium qui iure non maiores. Libero ut repudiandae tempora quae quia.",
  },
  {
    id: 3,
    title: "rerum qui aut",
    assigneeId: 2,
    startDate: "2024-04-30T15:07:14.223Z",
    endDate: "2025-01-18T20:37:07.673Z",
    prority: "3",
    labels: ["2", "4", "2"],
    description:
      "Aut architecto dolorum sunt. Nemo doloribus dolorem veniam fugiat repudiandae ex aut et fugiat. Et occaecati unde minima voluptatum explicabo. Iure occaecati quia ea sint odit voluptatem. Perspiciatis aut pariatur qui blanditiis est ut facilis quisquam deleniti. Ullam esse omnis rerum odio.",
  },
  {
    id: 4,
    title: "soluta ea facere",
    assigneeId: 9,
    startDate: "2024-04-30T19:58:44.927Z",
    endDate: "2024-07-26T06:29:35.980Z",
    prority: "2",
    labels: ["1"],
    description:
      "Beatae aut quo est sint ut odio optio repellendus quo. Vel ut quaerat totam quas odio corrupti ut dolor. Reiciendis id sint est fugiat et.",
  },
  {
    id: 5,
    title: "aspernatur fuga omnis",
    assigneeId: 7,
    startDate: "2024-05-01T05:06:30.430Z",
    endDate: "2024-10-23T08:35:26.465Z",
    prority: "1",
    labels: ["3"],
    description:
      "Quasi ut ut adipisci. Ratione odio nesciunt ut quo ad vero sapiente vel magnam. Dolores ratione maiores. Iste molestiae voluptatum deserunt autem. Non ut ipsum recusandae ea perferendis ea molestiae repellat.",
  },
  {
    id: 6,
    title: "similique reprehenderit fuga",
    assigneeId: 6,
    startDate: "2024-05-01T09:35:18.431Z",
    endDate: "2025-03-08T20:41:39.444Z",
    prority: "2",
    labels: ["2", "4", "1"],
    description:
      "Eaque quis voluptas aut dolorem omnis rerum. Impedit sint reiciendis nihil quia sed cum qui quis. Rerum itaque sunt sint. Quasi et quaerat rem ut labore voluptas. Nisi sapiente est optio.",
  },
  {
    id: 7,
    title: "et consequatur dolorem",
    assigneeId: 9,
    startDate: "2024-05-01T06:15:01.165Z",
    endDate: "2025-03-05T10:50:41.008Z",
    prority: "3",
    labels: ["3", "4"],
    description:
      "Nulla blanditiis quaerat. Labore necessitatibus eveniet velit dignissimos tempora quasi modi deleniti aut. Aut maxime explicabo nam eum.",
  },
  {
    id: 8,
    title: "perferendis dolorum sed",
    assigneeId: 10,
    startDate: "2024-04-30T18:30:22.759Z",
    endDate: "2025-04-06T03:35:25.456Z",
    prority: "3",
    labels: ["2"],
    description:
      "Omnis officiis rerum voluptatem tenetur. Sit eius eum animi voluptatem laudantium quo perferendis numquam commodi. Molestiae eum modi magnam totam itaque quo eos corrupti dicta. Et sint sunt aut et non. Cupiditate libero quia aut unde sunt.",
  },
  {
    id: 9,
    title: "hic praesentium aliquid",
    assigneeId: 7,
    startDate: "2024-05-01T05:00:03.367Z",
    endDate: "2024-05-03T17:10:07.842Z",
    prority: "2",
    labels: ["1"],
    description:
      "Doloribus sed eos aut. Aut fuga nesciunt id occaecati libero. Laudantium iusto eveniet earum labore reiciendis aut. Numquam ducimus cumque enim veritatis veniam earum.",
  },
  {
    id: 10,
    title: "corporis cumque quos",
    assigneeId: 5,
    startDate: "2024-05-01T04:50:27.704Z",
    endDate: "2024-07-14T02:10:53.688Z",
    prority: "1",
    labels: ["4", "1", "1"],
    description:
      "Nihil rerum enim facere quidem iusto aliquam libero distinctio. Voluptates voluptas inventore. Animi enim reiciendis quod.",
  },
  {
    id: 11,
    title: "nam quia placeat",
    assigneeId: 8,
    startDate: "2024-05-01T07:14:48.373Z",
    endDate: "2025-03-24T10:06:47.588Z",
    prority: "3",
    labels: ["1"],
    description:
      "Molestiae odit qui minus voluptatum rem dolorem tempora. Fugiat nihil non aut ducimus odit porro. Vitae repellat in consequatur beatae. Inventore facilis sint illo vel et modi deleniti. Veritatis possimus earum placeat nemo explicabo.",
  },
  {
    id: 12,
    title: "officiis commodi quis",
    assigneeId: 4,
    startDate: "2024-04-30T19:08:58.629Z",
    endDate: "2024-11-30T13:28:02.141Z",
    prority: "3",
    labels: ["3"],
    description:
      "Sint eaque omnis. Eum ab quas dolor cum. Ut similique assumenda aut laudantium voluptatum repellendus ducimus eos magnam. Consequatur aut delectus deserunt distinctio assumenda qui.",
  },
  {
    id: 13,
    title: "dolorem vero explicabo",
    assigneeId: 8,
    startDate: "2024-04-30T15:52:04.985Z",
    endDate: "2025-01-05T09:08:06.512Z",
    prority: "2",
    labels: ["1", "2", "3"],
    description:
      "Qui quia id nemo harum id exercitationem optio vel. Adipisci quibusdam ut eum quod repellendus officia exercitationem qui quaerat. Saepe rerum vel quae. Inventore vitae voluptate quis nisi velit modi. Possimus similique voluptatem odio quia sapiente ea.",
  },
  {
    id: 14,
    title: "debitis modi labore",
    assigneeId: 5,
    startDate: "2024-05-01T10:43:17.957Z",
    endDate: "2024-12-14T14:56:34.343Z",
    prority: "1",
    labels: ["2"],
    description:
      "Magnam dolorem est facilis est omnis est. Quasi sed ut adipisci voluptatem voluptatum fugit labore veniam. Ea sapiente voluptatem quis nisi deleniti nihil deleniti. Ipsam sit dolores et aut dolore. Sapiente excepturi sit distinctio explicabo. Eum asperiores nihil error accusantium sint tempore dolores necessitatibus.",
  },
  {
    id: 15,
    title: "quia ut necessitatibus",
    assigneeId: 3,
    startDate: "2024-05-01T04:54:40.638Z",
    endDate: "2024-07-20T06:07:46.213Z",
    prority: "2",
    labels: ["3"],
    description:
      "Eos dolor impedit eaque sit ducimus. Aut eligendi molestias omnis et accusantium. Eos id omnis.",
  },
  {
    id: 16,
    title: "odit ut aut",
    assigneeId: 3,
    startDate: "2024-04-30T20:29:54.245Z",
    endDate: "2024-08-24T10:19:01.284Z",
    prority: "1",
    labels: ["3"],
    description:
      "Autem animi earum eligendi est molestiae. Reprehenderit quo error sit incidunt. Et molestiae ipsam dicta iure ut illum consectetur. Eum quia in aut quod ea ea voluptatem voluptatem quis. Fugit delectus eaque rerum.",
  },
  {
    id: 17,
    title: "omnis non laboriosam",
    assigneeId: 3,
    startDate: "2024-05-01T00:30:03.615Z",
    endDate: "2024-11-10T03:50:14.587Z",
    prority: "1",
    labels: ["3", "3"],
    description:
      "Architecto veritatis autem maiores. Voluptas pariatur et sit natus ab ea in dolorum. Tenetur culpa consequatur omnis et consequatur qui voluptates aut temporibus. Aperiam laboriosam nemo quo cum.",
  },
  {
    id: 18,
    title: "et dolor quod",
    assigneeId: 8,
    startDate: "2024-04-30T21:45:38.852Z",
    endDate: "2024-11-17T05:57:49.491Z",
    prority: "2",
    labels: ["4"],
    description:
      "Omnis cum eveniet occaecati nisi accusamus illum. Nesciunt voluptate molestiae. Est maiores suscipit veniam qui. Ut est enim debitis commodi modi voluptatem quidem doloremque nam. Voluptatem beatae dolorum et quo laboriosam consequatur alias accusantium.",
  },
  {
    id: 19,
    title: "sunt sit quia",
    assigneeId: 10,
    startDate: "2024-04-30T23:07:04.505Z",
    endDate: "2025-03-26T14:11:36.104Z",
    prority: "1",
    labels: ["1", "1"],
    description:
      "Ipsam in molestiae aspernatur cumque corrupti ipsa. Quo eligendi qui. Mollitia tempore voluptatibus est tenetur vel quas et. Ipsa sunt eum fugiat nulla ut vero. Animi eum enim aperiam corrupti.",
  },
  {
    id: 20,
    title: "beatae nobis quas",
    assigneeId: 4,
    startDate: "2024-04-30T21:17:54.044Z",
    endDate: "2024-11-17T20:38:28.184Z",
    prority: "3",
    labels: ["1"],
    description:
      "Voluptatem assumenda dolor architecto repellendus ab aperiam nulla rerum. Sit quibusdam similique dolore voluptas et qui sequi fugit. Ad architecto maxime voluptas. Fugit doloribus et pariatur similique quisquam recusandae dignissimos nam dolor. Laborum est maiores fugit magni. Qui omnis excepturi ratione repellendus ipsum.",
  },
  {
    id: 21,
    title: "ut dolore explicabo",
    assigneeId: 2,
    startDate: "2024-04-30T23:35:36.813Z",
    endDate: "2024-11-23T21:14:48.418Z",
    prority: "3",
    labels: ["1"],
    description:
      "Magni at quia exercitationem sit tempora magnam est. Voluptatem quas itaque nam totam itaque incidunt. Rerum inventore impedit hic laudantium sint culpa fugit. Totam non est repudiandae. Nostrum fugit officiis qui ullam quod maiores quasi et et. A natus rem quod soluta est in.",
  },
  {
    id: 22,
    title: "delectus repellat ad",
    assigneeId: 7,
    startDate: "2024-04-30T21:56:29.972Z",
    endDate: "2024-09-27T15:03:37.581Z",
    prority: "2",
    labels: ["1"],
    description:
      "Voluptatem sit harum omnis. Ab iure velit velit quasi saepe at commodi aut est. Itaque itaque cum voluptatem recusandae qui.",
  },
  {
    id: 23,
    title: "laudantium deleniti libero",
    assigneeId: 10,
    startDate: "2024-04-30T16:02:40.620Z",
    endDate: "2025-04-08T02:09:21.473Z",
    prority: "2",
    labels: ["3"],
    description:
      "Quaerat nihil ut qui cum eum accusamus dolores commodi. Voluptatem vel eos aut a. Perspiciatis quidem dolore quos nihil. Harum quo tempore dolorem maiores sit tempore et unde quasi. Sint id molestiae odit rerum laborum aspernatur. Sint a sequi quo.",
  },
  {
    id: 24,
    title: "ipsam aliquam accusamus",
    assigneeId: 7,
    startDate: "2024-04-30T12:51:01.480Z",
    endDate: "2024-11-27T08:14:10.794Z",
    prority: "3",
    labels: ["3", "4"],
    description:
      "Minima ab eaque nulla possimus magni cumque sit dignissimos. Cumque et numquam est perferendis. Officia ut itaque. Ut ut facere cumque tempora ea delectus facere deserunt. Delectus quidem qui voluptatem ut est doloremque aut recusandae consequatur.",
  },
  {
    id: 25,
    title: "temporibus consequatur maiores",
    assigneeId: 3,
    startDate: "2024-05-01T04:06:24.225Z",
    endDate: "2024-08-01T22:40:41.278Z",
    prority: "2",
    labels: ["3"],
    description:
      "Deleniti consequatur in vitae deleniti quae. Natus consequatur inventore dolores recusandae repellat est perferendis. Doloremque laudantium quia rerum ipsum deleniti et consequuntur ducimus architecto.",
  },
  {
    id: 26,
    title: "quod enim quos",
    assigneeId: 9,
    startDate: "2024-04-30T23:35:54.952Z",
    endDate: "2024-11-30T10:52:59.848Z",
    prority: "3",
    labels: ["2", "1"],
    description:
      "Porro laborum vel dolor possimus non facilis. Placeat corrupti unde sit aut beatae. Blanditiis consequuntur consequatur omnis ad sunt commodi et. Mollitia molestiae quidem et eum. Amet dignissimos placeat quam nesciunt. Eius aut et sunt libero.",
  },
  {
    id: 27,
    title: "aspernatur qui architecto",
    assigneeId: 10,
    startDate: "2024-04-30T13:50:08.563Z",
    endDate: "2025-04-08T02:16:56.395Z",
    prority: "3",
    labels: ["2", "4"],
    description:
      "Atque iure voluptatibus quas quod accusantium ut voluptas. Nobis eius animi itaque neque enim vel. Temporibus quasi sint ratione et voluptatem quia dolores. Et quaerat expedita quidem quisquam eos et suscipit quam id. Beatae doloribus unde ut et magnam et neque.",
  },
  {
    id: 28,
    title: "veritatis enim fugiat",
    assigneeId: 8,
    startDate: "2024-05-01T01:39:49.367Z",
    endDate: "2024-12-27T09:48:32.472Z",
    prority: "2",
    labels: ["3", "2", "2"],
    description:
      "Saepe ea laudantium voluptate quasi laudantium est. Maiores vel hic tenetur non aut vero in autem perspiciatis. Sit est natus pariatur autem ut et eos. Suscipit sed et eaque repudiandae labore sint. Laboriosam est ut commodi voluptas dicta assumenda nulla iste.",
  },
  {
    id: 29,
    title: "voluptate quo nemo",
    assigneeId: 9,
    startDate: "2024-05-01T09:47:16.158Z",
    endDate: "2024-05-21T23:26:49.384Z",
    prority: "1",
    labels: ["3", "4", "4"],
    description:
      "Ut delectus distinctio corrupti. Ut laborum iure maxime sed nihil qui perspiciatis alias ut. Officiis sequi veritatis magnam iusto consequatur. Sit temporibus natus doloribus aspernatur deleniti. Et id suscipit rerum. Provident facere velit et soluta rerum.",
  },
  {
    id: 30,
    title: "natus sit est",
    assigneeId: 6,
    startDate: "2024-04-30T20:46:34.634Z",
    endDate: "2024-10-22T06:58:03.636Z",
    prority: "3",
    labels: ["4", "2", "3"],
    description:
      "Qui laboriosam sit aut voluptas quod suscipit ea rem consectetur. Fugiat dolores molestias quaerat repellat porro qui soluta tenetur. Ex praesentium quia pariatur autem ut esse id alias voluptates. Et necessitatibus id iste sed optio. Deserunt ea et voluptatem. Dolores quasi at voluptates.",
  },
];
